export interface HeroVariation {
  headline: string
  subheadline: string
  accentColor: string   // Tailwind class for keyword highlight
  gradientFrom: string  // CSS color for gradient start
  gradientTo: string    // CSS color for gradient end
  patternColor: string  // CSS color for dot pattern
}

// Filipino-centric color palette:
// Gold #C8A951 - Philippine sun, generosity
// Philippine Red #C8102E - courage, bayanihan spirit  
// Trust Blue #2B4C7E - Philippine waters, dependability
// Emerald #006B3F - Philippine landscapes, growth
// Sunshine #F5A623 - optimism, warmth
// Deep Navy #0A1F44 - trust, depth

const accentColors = {
  gold: 'text-[#C8A951]',
  red: 'text-[#C8102E]',
  blue: 'text-[#2B4C7E]',
  emerald: 'text-[#006B3F]',
  sunshine: 'text-[#F5A623]',
}

export const heroVariations: Record<string, HeroVariation[]> = {
  home: [
    {
      headline: 'The {Trust} Layer for Filipino Giving',
      subheadline: 'Fundraise.ph is a nonprofit technology organization building the trusted fundraising infrastructure for Filipinos worldwide — strengthening bayanihan through transparency, verification, and accountable digital giving.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Bayanihan} Deserves Modern Infrastructure',
      subheadline: 'For generations, Filipinos have supported one another. Fundraise.ph builds the trust layer that makes online fundraising safer, clearer, and more accountable for every Filipino community.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Every Help Should {Count}',
      subheadline: 'Fundraise.ph ensures that every donation is verified, every campaign is documented, and every act of Filipino generosity is honored with transparency and accountability.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Technology for {Bayanihan}',
      subheadline: 'We build and maintain the digital infrastructure that powers trusted Filipino fundraising — from verification engines to marketplace tools — ensuring bayanihan thrives in the digital age.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Raising {Standards} for Filipino Fundraising',
      subheadline: 'Fundraise.ph is not just about raising funds. It is about raising standards — building the trusted, transparent, and compliant infrastructure that Filipino giving deserves.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'why-we-exist': [
    {
      headline: '{Bayanihan} is Powerful. Trust Makes It Scalable.',
      subheadline: 'Fundraise.ph was created because Filipino generosity deserves modern infrastructure built on verification, documentation, and accountability.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Closing the {Trust Gap} in Filipino Fundraising',
      subheadline: 'Online fundraising has created new challenges. Fundraise.ph exists to close the trust gap between generous Filipinos and the campaigns that need their support.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Filipinos Are {Generous}. Online Giving Needs Trust.',
      subheadline: 'The Philippines is one of the most generous nations on earth. We exist to ensure that generosity is met with verification, transparency, and accountability.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From Good Intentions to {Trusted Action}',
      subheadline: 'Fundraise.ph bridges the gap between the desire to help and the confidence to give — building systems that make Filipino generosity safer and more effective.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Every} Donation Deserves a Trail of Trust',
      subheadline: 'We exist because every peso given in trust should be traceable, every beneficiary should be verified, and every campaign should be accountable.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  mission: [
    {
      headline: 'Strengthening {Bayanihan} Through Trust and Technology',
      subheadline: 'Our mission: build trusted, transparent, compliant, and technology-enabled fundraising infrastructure for Filipinos worldwide.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'The Most {Trusted} Nonprofit for Filipino Fundraising',
      subheadline: 'Our vision: to become the most trusted nonprofit technology institution supporting Filipino fundraising and crowdfunding globally.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Building {Public Trust} in Filipino Digital Giving',
      subheadline: 'Seven objectives guide our work — from building verification standards to supporting Filipinos worldwide with trustworthy fundraising technology.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Technology-Enabled {Transparency} for Every Campaign',
      subheadline: 'We use modern software, AI, automation, and verification workflows to make fundraising easier, safer, and more transparent for Filipinos.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Compliance} Without Killing Bayanihan',
      subheadline: 'We strengthen compliance awareness while preserving the Filipino spirit of giving — helping campaigners understand responsible fundraising.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'trust-transparency': [
    {
      headline: 'Trust Is Not a {Slogan}. Trust Is a System.',
      subheadline: 'Fundraise.ph is committed to building fundraising infrastructure based on transparency, documentation, governance, verification, reporting, and accountability.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Verify}. Guide. Track. Report. Improve.',
      subheadline: 'Our five-step trust framework ensures every campaign is reviewed, guided, tracked, reported, and continuously improved.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Transparency} by Default, Not by Exception',
      subheadline: 'We publish organizational identity, governance information, annual reports, campaign standards, and verification methodology — because trust requires openness.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Building {Audit Trails}, Not Confusion',
      subheadline: 'Technology should create clarity, not complexity. We build systems that produce verifiable records, transparent fund flows, and donor acknowledgments.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Donors Should {Know} What They Are Supporting',
      subheadline: 'We believe in informed giving — where supporters understand campaign details, fund destinations, and verification status before they contribute.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'technology-roadmap': [
    {
      headline: 'Building the {Technology} Infrastructure for Digital Bayanihan',
      subheadline: 'Our phased approach ensures every feature is built on a foundation of trust, compliance, and community impact.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'From {Verification} to AI-Assisted Trust',
      subheadline: 'Eight phases of development — from nonprofit foundation to institutional partnerships — each strengthening the trust layer for Filipino giving.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Marketplace} Fundraising Meets Filipino Community',
      subheadline: 'Product-based fundraising, sponsor participation, and diaspora giving tools — all built on a foundation of verification and transparency.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: '{AI} Should Assist, Not Replace, Human Governance',
      subheadline: 'Our roadmap includes AI-powered campaign guidance, compliance checklists, and fraud detection — always with human oversight and accountability.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Every Phase Built on {Trust}',
      subheadline: 'From nonprofit incorporation to full trust infrastructure, each phase of our roadmap is designed with transparency and community at its core.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'founding-story': [
    {
      headline: 'From {Bayanihan} to Digital Trust Infrastructure',
      subheadline: 'Fundraise.ph was born from a simple realization: Filipinos are generous, but generosity needs trust to scale.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'A New Model of {Filipino} Fundraising',
      subheadline: 'Not just crowdfunding. Not just donations. Not just software. But a trust-first fundraising infrastructure built for Filipinos worldwide.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'The Idea That {Generosity} Deserves Better',
      subheadline: 'The idea started with the need to create a Filipino-first fundraising system that could support real campaigns, real communities, and real beneficiaries.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Real {Trust} for Real Communities',
      subheadline: 'Fundraise.ph was created as the nonprofit mission organization behind a movement to make Filipino fundraising safer, clearer, and more trusted.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'From a {Simple Realization} to a National Mission',
      subheadline: 'What began as an observation about the trust gap in Filipino online fundraising became a commitment to build infrastructure that honors every act of bayanihan.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'sergs-chocolates': [
    {
      headline: 'From Filipino {Chocolate Heritage} to Bayanihan Infrastructure',
      subheadline: "Serg's Chocolates is more than a chocolate brand. For many Filipinos, it is part of childhood, family memory, pasalubong culture, and the simple joy of giving.",
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'A Chocolate Bar Can Be {Bayanihan}',
      subheadline: "Through Fundraise.ph and Fundraising.ph, Serg's Chocolates can become part of a modern giving movement — where products support causes with trust.",
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Pasalubong} Culture Meets Marketplace Fundraising',
      subheadline: "A chocolate bar can be a pasalubong, a thank-you gift, a family memory, a reward, or a small act of care. Now it can also be a small act of bayanihan.",
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: '{Filipino} Heritage Brands Supporting Filipino Causes',
      subheadline: "Serg's Chocolates can become one of the founding examples of how Filipino products can support Filipino causes through trusted, transparent marketplace fundraising.",
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'From Chocolate to {Community}',
      subheadline: "If Filipinos want to support the revival of a beloved heritage brand, they should be able to do so transparently. Serg's Chocolates proves that culture, commerce, and compassion can work together.",
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  team: [
    {
      headline: 'Guided by People Committed to {Trust} and Filipino Impact',
      subheadline: 'Our trustees and team members are committed to transparency, technology, and building trustworthy fundraising infrastructure for Filipino communities.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Governance} That Earns Public Confidence',
      subheadline: 'Every trustee role is designed to provide oversight, accountability, and expertise in areas critical to building trusted Filipino fundraising infrastructure.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Human {Oversight} Over Every Automated Decision',
      subheadline: 'Technology assists our work, but sensitive decisions remain accountable to people — trustees who are committed to beneficiary dignity and public trust.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Protecting {Beneficiary} Dignity and Donor Trust',
      subheadline: 'From compliance oversight to community partnerships, our trustee structure ensures every stakeholder in the fundraising ecosystem is represented and protected.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'The {People} Behind the Trust Layer',
      subheadline: 'Fundraise.ph is led by professionals in governance, technology, finance, compliance, community, and ethics — each committed to building the future of Filipino giving.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  governance: [
    {
      headline: 'Public Trust Begins with {Internal Discipline}',
      subheadline: 'Every program, partnership, and technology decision must support trusted Filipino fundraising. Our governance principles ensure mission alignment.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Transparency} by Default, Not by Choice',
      subheadline: 'Public information should be accessible whenever possible. We publish our governance policies, conflict-of-interest rules, and decision-making frameworks.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Beneficiary} Dignity Is Non-Negotiable',
      subheadline: 'Campaigns must respect consent, privacy, and human dignity. Our governance framework ensures ethical storytelling and protection of vulnerable individuals.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Human Judgment Over {AI} Automation',
      subheadline: 'AI may assist with review, reporting, and risk detection, but sensitive decisions must remain accountable to humans — always overseen by our trustees.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Compliance}-Aware Operations at Every Level',
      subheadline: 'We support responsible fundraising by educating campaigners and partners about documentation, permits, privacy, and reporting expectations.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  impact: [
    {
      headline: 'Impact Is Not Only Money Raised. Impact Is {Trust Created}.',
      subheadline: 'We measure success not just by funds raised, but by the trust, verification, transparency, and accountability we build into every campaign.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Every} Act of Help Should Be Counted',
      subheadline: 'From campaign verification to donor acknowledgment, every step in our process is designed to ensure that help is tracked, recognized, and accountable.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Verified} Campaigns. Acknowledged Donors. Accountable Results.',
      subheadline: 'Our impact metrics track campaigns launched, donors acknowledged, beneficiaries assisted, and trust indicators — building measurable confidence in Filipino giving.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From {Donation} to Proof of Delivery',
      subheadline: 'Trust means following through. We track campaign completion rates, post-campaign reports, proof of delivery, and beneficiary updates to ensure accountability.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Building a {Transparent} Ecosystem of Filipino Giving',
      subheadline: 'Our future public dashboard will show total campaigns, verified campaigns, marketplace impact, and transparency scorecards — making trust visible.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'partner-with-us': [
    {
      headline: 'Help Build the {Trusted} Fundraising Infrastructure for Filipinos',
      subheadline: 'Whether you are a nonprofit, school, church, sponsor, supplier, or diaspora group — Fundraise.ph invites you to help build the future of Filipino giving.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Bayanihan} Works Best When We Work Together',
      subheadline: 'From NGOs to corporate sponsors, from schools to diaspora organizations — every partner strengthens the trust layer that protects Filipino generosity.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Your {Partnership} Builds Trust for Millions of Filipinos',
      subheadline: 'Partners provide the reach, expertise, and community connections that make trusted fundraising possible at scale across the Philippines and worldwide.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From {Corporate Sponsor} to Community Champion',
      subheadline: 'Businesses can participate as sponsors, suppliers, marketplace partners, or campaign supporters — turning corporate social responsibility into transparent community impact.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Diaspora} Partners: Connecting Filipinos Worldwide to Home',
      subheadline: 'Overseas Filipino organizations can help make diaspora giving more transparent, verified, and connected — bridging the distance between generosity and impact.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  blog: [
    {
      headline: '{Insights} on Trust, Transparency, and Filipino Giving',
      subheadline: 'Trustee notes, compliance education, bayanihan stories, and technology updates from the Fundraise.ph team.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Why {Transparency} Must Be Built Before Scale',
      subheadline: 'Our trustee notes explore the principles, challenges, and decisions behind building the trust layer for Filipino fundraising.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Compliance Education for {Responsible} Fundraising',
      subheadline: 'From donation vs. sponsorship distinctions to permit guidance — helping Filipino campaigners understand responsible fundraising practices.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'How Filipino {Heritage Brands} Can Support Fundraising',
      subheadline: 'Exploring marketplace fundraising, product-based campaigns, and how Filipino businesses can participate in trusted community giving.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Building} Filipino Giving Infrastructure for the Next 50 Years',
      subheadline: 'Long-term thinking about AI governance, public trust, beneficiary dignity, and the future of digital bayanihan in the Philippines.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],
}
