export interface HeroVariation {
  headline: string
  subheadline: string
  accentColor: string   // Tailwind class for keyword highlight
  gradientFrom: string  // CSS color for gradient start
  gradientTo: string    // CSS color for gradient end
  patternColor: string  // CSS color for dot pattern
}

// Filipino-centric color palette:
// Gold #C8A951 - Philippine sun, generosity
// Philippine Red #C8102E - courage, bayanihan spirit  
// Trust Blue #2B4C7E - Philippine waters, dependability
// Emerald #006B3F - Philippine landscapes, growth
// Sunshine #F5A623 - optimism, warmth
// Deep Navy #0A1F44 - trust, depth

const accentColors = {
  gold: 'text-[#C8A951]',
  red: 'text-[#C8102E]',
  blue: 'text-[#2B4C7E]',
  emerald: 'text-[#006B3F]',
  sunshine: 'text-[#F5A623]',
}

export const heroVariations: Record<string, HeroVariation[]> = {
  home: [
    {
      headline: 'The {Trust} Layer for Filipino Giving',
      subheadline: 'Fundraise.ph is a nonprofit technology organization building the trusted fundraising infrastructure for Filipinos worldwide — strengthening bayanihan through transparency, verification, and accountable digital giving.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Bayanihan} Deserves Modern Infrastructure',
      subheadline: 'For generations, Filipinos have supported one another. Fundraise.ph builds the trust layer that makes online fundraising safer, clearer, and more accountable for every Filipino community.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Every Help Should {Count}',
      subheadline: 'Fundraise.ph ensures that every donation is verified, every campaign is documented, and every act of Filipino generosity is honored with transparency and accountability.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Technology for {Bayanihan}',
      subheadline: 'We build and maintain the digital infrastructure that powers trusted Filipino fundraising — from verification engines to marketplace tools — ensuring bayanihan thrives in the digital age.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Raising {Standards} for Filipino Fundraising',
      subheadline: 'Fundraise.ph is not just about raising funds. It is about raising standards — building the trusted, transparent, and compliant infrastructure that Filipino giving deserves.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'why-we-exist': [
    {
      headline: '{Bayanihan} is Powerful. Trust Makes It Scalable.',
      subheadline: 'Fundraise.ph was created because Filipino generosity deserves modern infrastructure built on verification, documentation, and accountability.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Closing the {Trust Gap} in Filipino Fundraising',
      subheadline: 'Online fundraising has created new challenges. Fundraise.ph exists to close the trust gap between generous Filipinos and the campaigns that need their support.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Filipinos Are {Generous}. Online Giving Needs Trust.',
      subheadline: 'The Philippines is one of the most generous nations on earth. We exist to ensure that generosity is met with verification, transparency, and accountability.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From Good Intentions to {Trusted Action}',
      subheadline: 'Fundraise.ph bridges the gap between the desire to help and the confidence to give — building systems that make Filipino generosity safer and more effective.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Every} Donation Deserves a Trail of Trust',
      subheadline: 'We exist because every peso given in trust should be traceable, every beneficiary should be verified, and every campaign should be accountable.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  mission: [
    {
      headline: 'Strengthening {Bayanihan} Through Trust and Technology',
      subheadline: 'Our mission: build trusted, transparent, compliant, and technology-enabled fundraising infrastructure for Filipinos worldwide.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'The Most {Trusted} Nonprofit for Filipino Fundraising',
      subheadline: 'Our vision: to become the most trusted nonprofit technology institution supporting Filipino fundraising and crowdfunding globally.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Building {Public Trust} in Filipino Digital Giving',
      subheadline: 'Seven objectives guide our work — from building verification standards to supporting Filipinos worldwide with trustworthy fundraising technology.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Technology-Enabled {Transparency} for Every Campaign',
      subheadline: 'We use modern software, AI, automation, and verification workflows to make fundraising easier, safer, and more transparent for Filipinos.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Compliance} Without Killing Bayanihan',
      subheadline: 'We strengthen compliance awareness while preserving the Filipino spirit of giving — helping campaigners understand responsible fundraising.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'trust-transparency': [
    {
      headline: 'Every act of help should be {visible}, acknowledged, and accountable.',
      subheadline: 'Trust & Transparency explains what the public, donors, supporters, partners, and campaign viewers should be able to see, understand, verify, and rely on when engaging with Fundraise.ph and Fundraising.ph.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Trust Is Not a {Slogan}. Trust Is a System.',
      subheadline: 'Fundraise.ph is committed to building fundraising infrastructure based on transparency, documentation, governance, verification, reporting, and accountability.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Transparency} by Default, Not by Exception',
      subheadline: 'We publish organizational identity, governance information, annual reports, campaign standards, and verification methodology — because trust requires openness.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Building {Audit Trails}, Not Confusion',
      subheadline: 'Technology should create clarity, not complexity. We build systems that produce verifiable records, transparent fund flows, and donor acknowledgments.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Donors Should {Know} What They Are Supporting',
      subheadline: 'We believe in informed giving — where supporters understand campaign details, fund destinations, and verification status before they contribute.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'technology-roadmap': [
    {
      headline: 'Building the {Technology} Infrastructure for Digital Bayanihan',
      subheadline: 'Our phased approach ensures every feature is built on a foundation of trust, compliance, and community impact.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'From {Verification} to Institutional Trust',
      subheadline: 'Nine phases of development — from nonprofit incorporation to open data and policy — each strengthening the trust layer for Filipino giving.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Marketplace} Fundraising Meets Filipino Community',
      subheadline: 'Product-based fundraising, sponsor participation, and diaspora giving tools — all built on a foundation of verification and transparency.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Human {Governance} Over Automation',
      subheadline: 'Our roadmap prioritizes human oversight, compliance checklists, and transparent reporting — always with accountability and community trust.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Every Phase Built on {Trust}',
      subheadline: 'From nonprofit incorporation to full trust infrastructure, each phase of our roadmap is designed with transparency and community at its core.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'technology-impact': [
    {
      headline: 'Technology for {bayanihan}. Impact built on trust.',
      subheadline: 'Fundraise.ph builds the technology infrastructure for trusted Filipino giving. Fundraising.ph is where campaigns come to life.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Building {Infrastructure} That Earns Trust',
      subheadline: 'From verification engines to marketplace tools, every technology decision at Fundraise.ph is made with transparency and accountability.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
    {
      headline: '{Impact} Measured, Not Claimed',
      subheadline: 'We measure what matters — verification rates, donor acknowledgment, campaign completion, and community trust — never inflating what we have not yet delivered.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
  ],

  'platform-infrastructure': [
    {
      headline: 'The {Operational Stack} Behind Fundraising.ph',
      subheadline: 'From campaign onboarding to audit trails, every component is designed for transparency, verification, and accountable fund management.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Infrastructure} That Serves the Mission',
      subheadline: 'Technology at Fundraise.ph exists to support trust — not to replace human judgment, bypass compliance, or automate accountability.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'ai-automation': [
    {
      headline: 'AI {assists}. Humans decide.',
      subheadline: 'Fundraise.ph uses AI to support review, guidance, reporting, and operational efficiency — never to replace human judgment, legal advice, or campaign-specific verification.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'AI Should {Support}, Not Replace, Human Governance',
      subheadline: 'Every AI-assisted feature at Fundraise.ph operates under human oversight. No automated legal conclusions. No auto-approvals for high-risk campaigns.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
  ],

  'marketplace-fundraising': [
    {
      headline: '{Marketplace} Fundraising: Products With Purpose',
      subheadline: 'Filipino creators and communities can sell products, accept pre-orders, and run sponsor-supported campaigns — with full transparency about how proceeds benefit campaigns.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'From {Purchase} to Purpose',
      subheadline: 'Marketplace fundraising lets supporters buy products that directly fund campaigns — with clear disclosure that transactions are purchases or sponsorships, not pure donations.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  'diaspora-giving-technology': [
    {
      headline: 'Connecting {Overseas Filipinos} to Trusted Campaigns',
      subheadline: 'Technology that helps overseas Filipinos discover, support, and track verified campaigns in their hometowns and across the Philippines.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Bayanihan} Without Borders',
      subheadline: 'Over 10 million overseas Filipinos deserve technology that makes giving back home transparent, verified, and compliance-aware.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'open-data-research': [
    {
      headline: 'Open {Data} That Protects Privacy',
      subheadline: 'Fundraise.ph will publish aggregated, anonymized trust metrics — never private donor data, sensitive beneficiary information, or personally identifiable information.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Research} for the Future of Filipino Giving',
      subheadline: 'Research briefs, trust metrics, and future API concepts — all built on privacy-protected, aggregated data.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
  ],

  'technology-governance': [
    {
      headline: 'Technology {governance} protects the mission.',
      subheadline: 'Privacy by design. Security by default. Human oversight over automation. These principles guide every technology decision at Fundraise.ph.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Trust} in Technology Requires Governance',
      subheadline: 'Every system, API, and AI tool must pass through technology governance review — ensuring auditability, data minimization, and beneficiary dignity.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'tech-faq': [
    {
      headline: 'Common questions about {technology} and impact.',
      subheadline: 'Answers about Fundraise.ph technology, AI, marketplace fundraising, impact measurement, and the Fundraising.ph platform.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Understanding the {Tech} Behind the Trust Layer',
      subheadline: 'What is Fundraise.ph? What is Fundraising.ph? How does AI work on the platform? Get clear, honest answers here.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'founding-story': [
    {
      headline: 'From {Chocolate Revival} to Digital Trust Infrastructure',
      subheadline: "Fundraise.ph was born from a chocolate brand that believed revival should serve community — and a platform gap that needed to be filled.",
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'A Chocolate Brand {Conceptualized} a Fundraising Platform',
      subheadline: "When Serg's Chocolates couldn't find a platform built for Filipino bayanihan, it built one. That platform became Fundraising.ph. The trust behind it became Fundraise.ph.",
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'From a {Brand Revival} to a National Mission',
      subheadline: "What started as Serg's Chocolates' plan to give back became Fundraise.ph — the nonprofit trust organization ensuring Filipino fundraising is done right.",
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: '{Bayanihan} Deserves a Platform Worthy of Its Sincerity',
      subheadline: "Serg's Chocolates proved that Filipino heritage brands can lead with purpose — and that purpose-built platforms can transform bayanihan culture for the digital age.",
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'The {Founding Story}: Chocolate, Purpose, and Trust',
      subheadline: "Serg's Chocolates is the Founding Member of Fundraise.ph — a living reminder that being Filipino means showing up for one another through bayanihan online.",
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'sergs-chocolates': [
    {
      headline: "The Chocolate Brand That {Conceptualized} Fundraising.ph",
      subheadline: "Serg's Chocolates didn't just inspire a platform — it conceptualized one. When the revival plan needed a fundraising platform that didn't exist, Serg's built it.",
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'A Revival with {Purpose}: CSR at the Core',
      subheadline: "Serg's Chocolates planned its comeback with giving back built into the business model — every bar of chocolate would also be an act of bayanihan.",
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{No Platform Existed}. So Serg\'s Built One.',
      subheadline: "No existing platform could support product-based community giving with verification, transparency, and Filipino bayanihan culture. So Serg's Chocolates conceptualized Fundraising.ph.",
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: '{Founding Member}: Serg\'s Reminds Us Why We Exist',
      subheadline: "As Fundraise.ph's Founding Member, Serg's Chocolates serves as a constant reminder that being Filipino means showing up for one another — and that bayanihan can live online.",
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'From {Chocolate} to Community Trust Infrastructure',
      subheadline: "A heritage brand's revival plan gave birth to a fundraising platform and a nonprofit trust organization — proving that Filipino businesses can lead with purpose.",
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  team: [
    {
      headline: 'Guided by People Committed to {Trust} and Filipino Impact',
      subheadline: 'Our trustees and team members are committed to transparency, technology, and building trustworthy fundraising infrastructure for Filipino communities.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Governance} That Earns Public Confidence',
      subheadline: 'Every trustee role is designed to provide oversight, accountability, and expertise in areas critical to building trusted Filipino fundraising infrastructure.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Human {Oversight} Over Every Automated Decision',
      subheadline: 'Technology assists our work, but sensitive decisions remain accountable to people — trustees who are committed to beneficiary dignity and public trust.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Protecting {Beneficiary} Dignity and Donor Trust',
      subheadline: 'From compliance oversight to community partnerships, our trustee structure ensures every stakeholder in the fundraising ecosystem is represented and protected.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'The {People} Behind the Trust Layer',
      subheadline: 'Fundraise.ph is led by professionals in governance, technology, finance, compliance, community, and ethics — each committed to building the future of Filipino giving.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  governance: [
    {
      headline: 'Public Trust Begins with {Internal Discipline}',
      subheadline: 'Every program, partnership, and technology decision must support trusted Filipino fundraising. Our governance principles ensure mission alignment.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Transparency} by Default, Not by Choice',
      subheadline: 'Public information should be accessible whenever possible. We publish our governance policies, conflict-of-interest rules, and decision-making frameworks.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Beneficiary} Dignity Is Non-Negotiable',
      subheadline: 'Campaigns must respect consent, privacy, and human dignity. Our governance framework ensures ethical storytelling and protection of vulnerable individuals.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'Human Judgment Over {AI} Automation',
      subheadline: 'AI may assist with review, reporting, and risk detection, but sensitive decisions must remain accountable to humans — always overseen by our trustees.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Compliance}-Aware Operations at Every Level',
      subheadline: 'We support responsible fundraising by educating campaigners and partners about documentation, permits, privacy, and reporting expectations.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  impact: [
    {
      headline: 'Impact Is Not Only Money Raised. Impact Is {Trust Created}.',
      subheadline: 'We measure success not just by funds raised, but by the trust, verification, transparency, and accountability we build into every campaign.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Every} Act of Help Should Be Counted',
      subheadline: 'From campaign verification to donor acknowledgment, every step in our process is designed to ensure that help is tracked, recognized, and accountable.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: '{Verified} Campaigns. Acknowledged Donors. Accountable Results.',
      subheadline: 'Our impact metrics track campaigns launched, donors acknowledged, beneficiaries assisted, and trust indicators — building measurable confidence in Filipino giving.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From {Donation} to Proof of Delivery',
      subheadline: 'Trust means following through. We track campaign completion rates, post-campaign reports, proof of delivery, and beneficiary updates to ensure accountability.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Building a {Transparent} Ecosystem of Filipino Giving',
      subheadline: 'Our future public dashboard will show total campaigns, verified campaigns, marketplace impact, and transparency scorecards — making trust visible.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'partner-with-us': [
    {
      headline: 'Help Build the {Trusted} Fundraising Infrastructure for Filipinos',
      subheadline: 'Whether you are a nonprofit, school, church, sponsor, supplier, or diaspora group — Fundraise.ph invites you to help build the future of Filipino giving.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Bayanihan} Works Best When We Work Together',
      subheadline: 'From NGOs to corporate sponsors, from schools to diaspora organizations — every partner strengthens the trust layer that protects Filipino generosity.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Your {Partnership} Builds Trust for Millions of Filipinos',
      subheadline: 'Partners provide the reach, expertise, and community connections that make trusted fundraising possible at scale across the Philippines and worldwide.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From {Corporate Sponsor} to Community Champion',
      subheadline: 'Businesses can participate as sponsors, suppliers, marketplace partners, or campaign supporters — turning corporate social responsibility into transparent community impact.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Diaspora} Partners: Connecting Filipinos Worldwide to Home',
      subheadline: 'Overseas Filipino organizations can help make diaspora giving more transparent, verified, and connected — bridging the distance between generosity and impact.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'partner-application': [
    {
      headline: 'Apply to Join the {Trusted} Fundraising Ecosystem',
      subheadline: 'Submit your partner application and help build the future of transparent, accountable Filipino fundraising. Every partnership strengthens trust for all.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Partner} With Fundraise.ph for Filipino Communities',
      subheadline: 'Join NGOs, schools, churches, corporations, and diaspora organizations committed to verified, transparent fundraising for Filipinos.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Your Organization Can {Strengthen} Trust in Giving',
      subheadline: 'Every partner commits to the same verification, transparency, and accountability standards. Together, we raise the bar for Filipino fundraising.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'From {Application} to Verified Partner',
      subheadline: 'A simple, transparent process: apply, get reviewed, onboard, and go live as a trusted partner in the Fundraise.ph ecosystem.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: 'Building {Bayanihan} Infrastructure Together',
      subheadline: 'Your partnership directly enables more Filipinos to access trusted fundraising — from local communities to the global diaspora.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  blog: [
    {
      headline: '{Insights} on Trust, Transparency, and Filipino Giving',
      subheadline: 'Trustee notes, compliance education, bayanihan stories, and technology updates from the Fundraise.ph team.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: 'Why {Transparency} Must Be Built Before Scale',
      subheadline: 'Our trustee notes explore the principles, challenges, and decisions behind building the trust layer for Filipino fundraising.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Compliance Education for {Responsible} Fundraising',
      subheadline: 'From donation vs. sponsorship distinctions to permit guidance — helping Filipino campaigners understand responsible fundraising practices.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
    {
      headline: 'How Filipino {Heritage Brands} Can Support Fundraising',
      subheadline: 'Exploring marketplace fundraising, product-based campaigns, and how Filipino businesses can participate in trusted community giving.',
      accentColor: accentColors.emerald,
      gradientFrom: '#0A1F44',
      gradientTo: '#0D2A50',
      patternColor: 'rgba(0, 107, 63, 0.07)',
    },
    {
      headline: '{Building} Filipino Giving Infrastructure for the Next 50 Years',
      subheadline: 'Long-term thinking about AI governance, public trust, beneficiary dignity, and the future of digital bayanihan in the Philippines.',
      accentColor: accentColors.blue,
      gradientFrom: '#0A1F44',
      gradientTo: '#162E54',
      patternColor: 'rgba(43, 76, 126, 0.08)',
    },
  ],

  'trust-governance-compliance': [
    {
      headline: 'Trust is not a slogan. It is the {system} behind every campaign.',
      subheadline: 'Fundraise.ph is building the nonprofit trust layer for Filipino giving. Our work is organized around three commitments: public transparency, strong governance, and compliance-aware fundraising.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Every} act of help should be counted, acknowledged, and protected.',
      subheadline: 'Donors deserve visibility, campaigners need guidance, beneficiaries deserve dignity, and the organization itself must be accountable.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Three {Pillars}: Trust, Governance, Compliance',
      subheadline: 'Fundraise.ph organizes its trust infrastructure around transparency, governance, and compliance — because responsible fundraising requires all three.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  compliance: [
    {
      headline: 'Responsible fundraising needs {clear guidance}.',
      subheadline: 'Fundraise.ph is not a regulator, law firm, payment institution, or government agency. But we believe fundraising platforms must be designed with compliance awareness from the beginning.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Compliance}-Aware, Not Compliance-Overwhelming',
      subheadline: 'Our compliance approach helps campaigners understand what type of campaign they are running, what documents may be needed, and when external review may be required.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Campaign {Classification} Protects Everyone',
      subheadline: 'When campaigners know what type of fundraising they are doing, donors know what to expect, and beneficiaries receive better protection.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  'verification-framework': [
    {
      headline: 'Verification should be {layered}, documented, and campaign-specific.',
      subheadline: 'Fundraise.ph defines multiple verification levels so that campaigns, donors, and partners can clearly understand what has been reviewed and what standards have been met.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Badges} That Mean Something',
      subheadline: 'Verification badges reflect the review level completed based on available documents and platform standards — not blanket guarantees.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'From {Identity} to Compliance Review',
      subheadline: 'Five verification levels — from basic identity review to compliance-sensitive review — ensure that every campaign gets the right level of scrutiny.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  'campaign-standards': [
    {
      headline: 'Raising funds responsibly starts with {clear standards}.',
      subheadline: 'Fundraise.ph promotes standards for campaign identity, documentation, donor communication, beneficiary consent, and post-campaign reporting.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Disclosure} Is the Foundation of Trust',
      subheadline: 'Campaigners must disclose who they are, what model they use, how funds will be spent, and what happens after the campaign closes.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'From {Launch} to Final Report',
      subheadline: 'Campaign standards cover the full lifecycle — from identity verification and documentation to post-campaign reporting and proof of delivery.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  policies: [
    {
      headline: 'Clear {policies} protect the mission and the public.',
      subheadline: 'Fundraise.ph maintains a growing public policy library covering governance, transparency, data protection, donor acknowledgment, campaign verification, and beneficiary dignity.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Transparency} by Default Means Published Policies',
      subheadline: 'Every governance policy, operational standard, and public commitment should be accessible — not hidden behind internal documents.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'Policies That {Serve} the Filipino Community',
      subheadline: 'Our policies are written to protect donors, campaigners, beneficiaries, and the public — not to create bureaucracy.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  'reports-disclosures': [
    {
      headline: 'Public accountability should be {visible} and accessible.',
      subheadline: 'Fundraise.ph is committed to publishing annual reports, financial summaries, trustee updates, impact reports, and governance disclosures.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Reports} Build Trust. Silence Builds Doubt.',
      subheadline: 'Regular public reporting ensures that donors, partners, and the community can verify that Fundraise.ph is meeting its commitments.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'From {Financial Summaries} to Impact Stories',
      subheadline: 'Transparency means showing both the numbers and the human impact — financial summaries alongside real campaign outcomes.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],

  faq: [
    {
      headline: 'Common {questions} about trust, governance, and compliance.',
      subheadline: 'Plain-English answers to the most important questions about Fundraise.ph, Fundraising.ph, verification, compliance, and responsible fundraising.',
      accentColor: accentColors.gold,
      gradientFrom: '#0A1F44',
      gradientTo: '#1A3A6B',
      patternColor: 'rgba(200, 169, 81, 0.08)',
    },
    {
      headline: '{Understanding} the Trust Layer for Filipino Giving',
      subheadline: 'What is Fundraise.ph? What is Fundraising.ph? What does verification mean? Get clear, honest answers here.',
      accentColor: accentColors.red,
      gradientFrom: '#0A1F44',
      gradientTo: '#1E2A4A',
      patternColor: 'rgba(200, 16, 46, 0.06)',
    },
    {
      headline: 'From {Compliance} to Campaign Verification',
      subheadline: 'Answers about our approach to responsible fundraising — without legal overclaims or regulatory guarantees.',
      accentColor: accentColors.sunshine,
      gradientFrom: '#0A1F44',
      gradientTo: '#142952',
      patternColor: 'rgba(245, 166, 35, 0.08)',
    },
  ],
}
